In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
result=[]
for num in arr:
    result.append(num ** 2)

In [5]:
result

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]

In [6]:
print(result)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [9]:
result = arr**2 #vectorization

In [10]:
result

array([ 1,  4,  9, 16, 25])

result + 10

In [11]:
result

array([ 1,  4,  9, 16, 25])

In [12]:
result + [10, 10, 10, 10, 10]

array([11, 14, 19, 26, 35])

In [13]:
arr1=np.array([1,2,3])#One D array
arr2 = np.array([10, 20, 30])
res = arr1 + arr2

In [14]:
res

array([11, 22, 33])

In [15]:
arr3 = np.array([
    [1,2,3],
    [4,5,6]
])
arr4 = np.array([1,2,3])
res = arr3 + arr4

In [16]:
res

array([[2, 4, 6],
       [5, 7, 9]])

In [17]:
data = np.array([
    [10, 20, 30],
    [15,25,35],
    [20,30,40],
    [25,35,45],
    [30,40,50]
])

In [18]:
data

array([[10, 20, 30],
       [15, 25, 35],
       [20, 30, 40],
       [25, 35, 45],
       [30, 40, 50]])

In [19]:
mean = data.mean(axis = 1)

In [20]:
mean

array([20., 25., 30., 35., 40.])

In [21]:
std = data.std(axis =0)

In [25]:
normalized_data = (data - mean) / std

In [26]:
 mean = data.mean(axis=0)
std = data.std(axis = 0)

normalized_data

In [27]:
normalized_data

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])