In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr = np.array([1, 2, 3])

In [4]:
arr

array([1, 2, 3])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4,6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.arange(1, 100, 9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [12]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [15]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [16]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
myarr.shape

(4, 3)

In [18]:
myarr.size

12

In [19]:
myarr.ndim

2

In [20]:
myarr.dtype

dtype('int64')

In [25]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], dtype = "float32")

In [26]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [28]:
n = myarr.astype("float64")

In [29]:
n.dtype

dtype('float64')

In [30]:
myarr.shape

(4, 3)

In [31]:
reshaped = myarr.reshape((3,4))

In [32]:
reshaped

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [33]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [37]:
myarr.reshape((2, 6))

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]], dtype=float32)

In [38]:
myarr.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
      dtype=float32)