In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [11,12,13]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
 flat = arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [6]:
flat[0]

np.int64(1)

In [7]:
flat[3]

np.int64(4)

In [8]:
flat[3:6]

array([4, 5, 6])

In [9]:
flat[:6]

array([1, 2, 3, 4, 5, 6])

In [14]:
flat[:5] #same as flat[0:5]

array([1, 2, 3, 4, 5])

In [11]:
flat[3:] #same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [12]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
flat[::2]

array([ 1,  3,  5,  7,  9, 12])

In [15]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [26]:
b = flat[3:7].copy()

In [27]:
b

array([4444,    5,    6,    7])

In [28]:
b[0] = 4444

In [29]:
b

array([4444,    5,    6,    7])

In [30]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   11,   12,
         13])

In [32]:
arr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [33]:
arr[[1,4,6]]

array([54,  2, 34])

In [34]:
arr[arr>3]

array([54, 23, 53, 34,  5,  6])

In [35]:
arr[arr>23]

array([54, 53, 34])