In [5]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr[0]

array([1, 2, 3])

In [8]:
arr[1]

array([4, 5, 6])

In [9]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [10]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [11]:
arr[0][1]

np.int64(2)

In [12]:
arr[0, 1]

np.int64(2)

In [13]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [22]:
arr3D =  np.array([
    [[1,2,3], 
     [4,5,6]],
                   
    [[7,8,9], 
     [10,11,12]]
])

In [23]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3D.shape

(2, 2, 3)

In [25]:
arr3D[0,1,2]

np.int64(6)

In [26]:
arr3D[:, 0, :]

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
arr3D[:, 0, 1]

array([2, 8])

In [28]:
arr3D[:, 0]

array([[1, 2, 3],
       [7, 8, 9]])

In [29]:
arr[:, 1]=0

In [30]:
arr3D[:, 1] = 0

In [31]:
arr3D

array([[[1, 2, 3],
        [0, 0, 0]],

       [[7, 8, 9],
        [0, 0, 0]]])

In [32]:
arr

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])