In [18]:
l1 = [1,2,4]
l2 = [6,7,8]
list(zip(l1,l2))

[(1, 6), (2, 7), (4, 8)]

In [16]:
#Using python lists

import numpy as np
import time

size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()
print(add[0:10])
print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.2508668899536133


In [17]:
#Using NumPy arrays
import numpy as np
import time

size = 1_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1+l2
end = time.time()
print(add[0:10])
print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.0548553466796875


In [19]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [22]:
arr = np.array([[1,2,3], [4,5,6]])

In [23]:
type(arr)

numpy.ndarray

In [24]:
arr.shape

(2, 3)

In [25]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("Numpy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
Numpy array size: 8000 bytes


In [26]:
#Using python lists

import numpy as np
import time

size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x ** 2 for x in l1]
end = time.time()
print(add[0:10])
print(end - start)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
0.12657856941223145


In [27]:
#Using NumPy arrays
import numpy as np
import time

size = 1_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 ** 2
end = time.time()
print(add[0:10])
print(end - start)

[ 0  1  4  9 16 25 36 49 64 81]
0.019182682037353516
